-- ============================================================================
-- POKÉMON CARD SCANNER - SUPABASE DATABASE SCHEMA
-- ============================================================================

-- 1. Tabelle für öffentliche Profildaten (für spätere Social Features)
-- ============================================================================
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index für schnelle Username-Suche
create index if not exists profiles_username_idx on public.profiles (username);

-- RLS für Profiles
alter table public.profiles enable row level security;

-- Jeder kann Profile sehen (für Social Features)
create policy "Public profiles are viewable by everyone"
  on public.profiles for select
  using (true);

-- User können nur ihr eigenes Profil updaten
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);


-- 2. Haupt-Tabelle für gesammelte Karten
-- ============================================================================
create table if not exists public.user_cards (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  
  -- Daten von der Pokémon TCG API
  api_card_id text not null,    -- z.B. "sv3pt5-151" (eindeutige API ID)
  name text not null,           -- z.B. "Mew ex"
  set_name text,                -- z.B. "151"
  card_number text,             -- z.B. "151/165"
  image_url text,               -- URL zum Kartenbild
  rarity text,                  -- z.B. "Double Rare", "Ultra Rare"
  
  -- User-spezifische Daten
  condition text default 'Near Mint' check (condition in ('Mint', 'Near Mint', 'Excellent', 'Good', 'Light Played', 'Played', 'Poor')),
  purchase_price_eur numeric(10, 2),        -- Kaufpreis in Euro
  current_market_price_eur numeric(10, 2),  -- Aktueller Marktwert
  quantity integer default 1 check (quantity >= 1),
  is_foil boolean default false,
  
  -- Metadaten
  notes text,  -- User-Notizen zur Karte
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes für Performance
create index if not exists user_cards_user_id_idx on public.user_cards (user_id);
create index if not exists user_cards_api_card_id_idx on public.user_cards (api_card_id);
create index if not exists user_cards_created_at_idx on public.user_cards (created_at desc);
create index if not exists user_cards_name_idx on public.user_cards using gin (name gin_trgm_ops);

-- Composite Index für schnelle User-Karten Lookups
create index if not exists user_cards_user_api_idx on public.user_cards (user_id, api_card_id);


-- 3. Row Level Security (RLS) Policies
-- ============================================================================
alter table public.user_cards enable row level security;

-- User können nur ihre EIGENEN Karten sehen
create policy "Users can view own cards"
  on public.user_cards for select
  using (auth.uid() = user_id);

-- User können nur Karten in ihre EIGENE Sammlung einfügen
create policy "Users can insert own cards"
  on public.user_cards for insert
  with check (auth.uid() = user_id);

-- User können nur ihre EIGENEN Karten updaten
create policy "Users can update own cards"
  on public.user_cards for update
  using (auth.uid() = user_id);

-- User können nur ihre EIGENEN Karten löschen
create policy "Users can delete own cards"
  on public.user_cards for delete
  using (auth.uid() = user_id);


-- 4. Automatische Timestamp-Updates
-- ============================================================================
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql security definer;

-- Trigger für user_cards
create trigger on_user_cards_updated
  before update on public.user_cards
  for each row
  execute procedure public.handle_updated_at();

-- Trigger für profiles
create trigger on_profiles_updated
  before update on public.profiles
  for each row
  execute procedure public.handle_updated_at();


-- 5. Automatische Profil-Erstellung bei Registrierung
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    split_part(new.email, '@', 1)  -- Username = Teil vor @
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger bei neuem User
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute procedure public.handle_new_user();


-- 6. Nützliche Views für Statistiken (Optional)
-- ============================================================================

-- View: Sammlung-Statistiken pro User
create or replace view public.user_collection_stats as
select
  user_id,
  count(*) as unique_cards,
  sum(quantity) as total_cards,
  count(distinct set_name) as unique_sets,
  sum(current_market_price_eur * quantity) as total_collection_value,
  avg(current_market_price_eur) as avg_card_value
from public.user_cards
group by user_id;

-- Grant View-Zugriff
grant select on public.user_collection_stats to authenticated;


-- 7. Funktion: Duplikat-Check vor Insert
-- ============================================================================
-- Verhindert, dass dieselbe Karte mehrfach hinzugefügt wird
-- (wird im Flutter-Code gehandhabt, aber als Backup)

create or replace function public.check_duplicate_card()
returns trigger as $$
begin
  if exists (
    select 1 from public.user_cards
    where user_id = new.user_id
    and api_card_id = new.api_card_id
  ) then
    raise exception 'Karte bereits in Sammlung vorhanden. Bitte Anzahl erhöhen.';
  end if;
  return new;
end;
$$ language plpgsql;

-- Optional: Trigger aktivieren wenn gewünscht
-- create trigger check_duplicate_before_insert
--   before insert on public.user_cards
--   for each row
--   execute procedure public.check_duplicate_card();


-- 8. Hilfsfunktionen für Flutter App
-- ============================================================================

-- Funktion: Hole Top-Wert-Karten eines Users
create or replace function public.get_top_value_cards(
  p_user_id uuid,
  p_limit int default 10
)
returns table (
  id bigint,
  name text,
  image_url text,
  total_value numeric
) as $$
begin
  return query
  select
    uc.id,
    uc.name,
    uc.image_url,
    (uc.current_market_price_eur * uc.quantity) as total_value
  from public.user_cards uc
  where uc.user_id = p_user_id
    and uc.current_market_price_eur is not null
  order by total_value desc
  limit p_limit;
end;
$$ language plpgsql security definer;

-- Grant Zugriff
grant execute on function public.get_top_value_cards to authenticated;


-- ============================================================================
-- SETUP KOMPLETT ✅
-- ============================================================================

-- NEXT STEPS:
-- 1. Führe dieses SQL in deinem Supabase SQL Editor aus
-- 2. Gehe zu "Authentication" > "Policies" und überprüfe RLS
-- 3. Teste mit einem Test-User
-- 4. Fertig! 🚀